# Generated by Django 4.1.10 on 2023-08-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appmedium', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostCreate',
        ),
    ]
