# Generated by Django 4.1.10 on 2023-08-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmedium', '0002_rename_post_postcreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreate',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
