# Generated by Django 4.1.10 on 2023-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmedium', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/person.png', upload_to='ProfilImage'),
        ),
    ]
