# Generated by Django 4.1.10 on 2023-08-28 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Appmedium', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profil',
        ),
    ]
