# Generated by Django 4.1.10 on 2023-08-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmedium', '0010_rename_profile_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default="{% static 'img/person.png' %}", upload_to='ProfilImage'),
        ),
    ]
